---
title: The Association Between Modern Media and Public Opinions
author: 
date: "September 25, 2015"
output: html_document
---

##Purpose of Study:  
For this study, I have referenced the Outlook On Life dataset. The purpose of this study is to examine whether modern media has an effect on the opinions of the citizens of the United States. The goals of this study are to (1) establish a relationship between Americans and media and (2) determine if American attitudes are swayed by the media.  

##Variables:  
Variables I have considered in my data include W1_A1 (how interested participants are in what is going on in politics and government), W1_A2 (have participants thought about the upcoming election of 2012 recently), W1_A11 (how many times participants have watched national news programs on TV or on the Internet in the past week), and W1_C1 (what do participants identify as: Democratic, Republican, Independent, or other).  

```{r comment = NA}

library(PDS)
library(dplyr)
OOL.sub <- OOL %>% 
   rename(InterestPol = W1_A1, ThoughtsElections = W1_A2, WatchNews = W1_A11, PoliticalAffil = W1_C1) %>%
   select(InterestPol, ThoughtsElections, WatchNews, PoliticalAffil)
summary(OOL.sub)
OOL.sub$InterestPol[OOL.sub$InterestPol == -1] <- NA
OOL.sub$InterestPol <- factor(OOL.sub$InterestPol,labels=c("Extremely Interested","Very Interested", "Moderately Interested", "Slightly Interested", "Not Interested"))
table(OOL.sub$InterestPol)
OOL.sub$ThoughtsElections[OOL.sub$ThoughtsElections == -1] <- NA
OOL.sub$ThoughtsElections <- factor(OOL.sub$ThoughtsElections,labels=c( "Quite a lot", "Somewhat a lot", "Somewhat a little", "Only a little", "Not at all"))
table(OOL.sub$ThoughtsElections)
OOL.sub$WatchNews[OOL.sub$WatchNews == -1] <- NA
OOL.sub$WatchNews <- factor(OOL.sub$WatchNews,labels=c ("None", "One Day", "Two Days", "Three Days", "Four Days", "Five Days", "Six Days", "Seven Days"))
table(OOL.sub$WatchNews)
OOL.sub$PoliticalAffil[OOL.sub$PoliticalAffil == -1] <- NA
OOL.sub$PoliticalAffil <- factor(OOL.sub$PoliticalAffil, labels=c("Republican", "Democratic", "Independent", "Something Else"))
table(OOL.sub$PoliticalAffil)

library(ggplot2)
g1 <- ggplot(data = na.omit(OOL.sub), aes(InterestPol)) +
  geom_bar(fill = c("magenta")) +
  labs(x = "", y = "Total Number", title = "How Interested Are You in Politics?") +
  theme_bw() + 
  theme(axis.text.x  = element_text(angle = 75, vjust = 0.5)) 
g1
g2 <- ggplot(data = na.omit(OOL.sub), aes(ThoughtsElections)) +
  geom_bar(fill = c("purple")) +
  labs(x = "", y = "Total Number", title = "Thoughts on Upcoming Elections (2012)?") +
  theme_bw() + 
  theme(axis.text.x  = element_text(angle = 75, vjust = 0.5)) 
g2

g3 <- ggplot(data = na.omit(OOL.sub), aes(WatchNews)) +
  geom_bar(fill = c("green")) +
  labs(x = "", y = "Total Number", title = "How Many Times a Week Do You Watch the News?") +
  theme_bw() + 
  theme(axis.text.x  = element_text(angle = 75, vjust = 0.5)) 
g3
g4 <- ggplot(data = na.omit(OOL.sub), aes(PoliticalAffil)) +
  geom_bar(fill = c("red")) +
  labs(x = "", y = "Total Number", title = "What Political Party Do You Affiliate Yourself With?") +
  theme_bw() + 
  theme(axis.text.x  = element_text(angle = 75, vjust = 0.5)) 
g4

